project: default
source:
  repoURL: 'git@github.com:IntVerse/intverse-trigger-mesh.git'
  path: Observability/metrics/
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: observability
syncPolicy:
  syncOptions:
    - CreateNamespace=true