project: default
source:
  repoURL: 'git@github.com:IntVerse/intverse-trigger-mesh.git'
  path: Observability/metrics/
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: observability
syncPolicy:
  syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triggermesh-stack-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: triggermesh-stack-metrics
spec:
  project: default
  source:
    repoURL: https://storage.googleapis.com/triggermesh-charts
    path: observability/metrics/
    targetRevision: HEAD
    chart: triggermesh
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: trigger-mesh
syncPolicy:
  syncOptions:
    - CreateNamespace=true
  retry:
    limit: 2
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m0s