project: default
source:
  repoURL: 'https://github.com/IntVerse/intverse-trigger-mesh.git'
  path: knative-serving
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: knative-serving
syncPolicy:
  syncOptions:
    - CreateNamespace=true
