apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources-prometheus
  namespace: monitoring
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus-triggermesh
      type: prometheus
      uid: prometheus
      url: http://prometheus-operated.monitoring.svc:9090
      access: proxy
      basicAuth: false
    - name: Tempo-triggermesh
      type: tempo
      uid: tempo
      url: http://tempo-stack.monitoring.svc:3200
      access: proxy
      basicAuth: false
    - name: Loki-triggermesh
      type: loki
      uid: loki
      url: http://loki-stack.monitoring.svc:3100
      access: proxy
      basicAuth: false
