project: default
source:
  repoURL: 'https://storage.googleapis.com/triggermesh-charts'
  targetRevision: 0.5.0
  helm:
    valueFiles:
      - values.yaml
  chart: knative-operator
destination:
  server: 'https://kubernetes.default.svc'
  namespace: knative-operator
syncPolicy: {}
