project: default
source:
  repoURL: 'https://prometheus-community.github.io/helm-charts'
  targetRevision: 45.10.1
  helm:
    valueFiles:
      - values.yaml
    values: 'skipCrds: true'
  chart: kube-prometheus-stack
destination:
  server: 'https://kubernetes.default.svc'
  namespace: monitoring
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true