project: default
source:
  repoURL: 'https://prometheus-community.github.io/helm-charts'
  targetRevision: 2.0.0
  helm:
    valueFiles:
      - values.yaml
  chart: prometheus-operator-crds
destination:
  server: 'https://kubernetes.default.svc'
  namespace: monitoring
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - Replace=true
    - CreateNamespace=true